/*
 * Copyright 2026 Rafal Niski
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package ai.velat.core.api

import ai.velat.core.domain.Token
import kotlinx.coroutines.flow.Flow

/**
 * Contract for an on-device language-model inference engine.
 *
 * Implementations wrap a specific runtime (MediaPipe LLM Inference,
 * llama.cpp, ExecuTorch, etc.) and expose a uniform Kotlin-native
 * streaming generation API to the rest of Velat.
 *
 * Lifecycle: implementations hold native resources (loaded model weights,
 * KV cache, native interpreter handles). Callers MUST invoke [close] when
 * the engine is no longer needed. The [AutoCloseable] base lets callers
 * use Kotlin's `use {}` for scoped lifetimes.
 *
 * Threading: implementations serialize generation internally. Concurrent
 * calls to [generate] may queue or fail with an `IllegalStateException`,
 * depending on the implementation. Callers should coordinate through a
 * higher-level component (e.g., the `sdk` module's `Velat` class) instead
 * of attempting concurrent generation directly.
 *
 * Example (conceptual):
 * ```
 * MediaPipeLlmEngine.fromAssets(context, "gemma-2b-int4.tflite").use { engine ->
 *     engine.warmup()
 *     engine.generate(
 *         prompt = "What is the capital of France?",
 *         options = GenerationOptions(temperature = 0.0f),
 *     ).collect { token ->
 *         print(token.text)
 *     }
 * }
 * ```
 */
public interface LlmEngine : AutoCloseable {
    /** Static information about the loaded model. */
    public val info: LlmEngineInfo

    /**
     * Preload the model into memory and run a tiny dummy generation so the
     * first user-visible response has lower latency. Optional — callers may
     * skip this and let the first [generate] call pay the cold-start cost.
     */
    public suspend fun warmup(): Result<Unit>

    /**
     * Stream tokens for the given prompt. The returned [Flow] emits each
     * [Token] as the model produces it; when the model finishes (stop
     * token reached, [GenerationOptions.maxTokens] hit, or cancelled),
     * the flow completes normally.
     *
     * Cancelling the collecting coroutine stops generation cleanly; no
     * further tokens are emitted and native resources are released.
     */
    public fun generate(prompt: String, options: GenerationOptions = GenerationOptions()): Flow<Token>

    /**
     * Reset any per-session state (KV cache, conversation history) on the
     * underlying engine. Equivalent to closing and re-opening a session
     * but cheaper because the model weights stay loaded.
     */
    public suspend fun reset(): Result<Unit>
}

/**
 * Static, runtime-invariant information about an [LlmEngine] instance.
 *
 * @property modelName Human-readable name of the loaded model (e.g., `"gemma-2-2b-int4"`).
 * @property contextSize Maximum number of tokens the model accepts as input + output combined.
 * @property maxOutputTokens Configured upper bound on tokens generated per [LlmEngine.generate] call.
 */
public data class LlmEngineInfo(
    public val modelName: String,
    public val contextSize: Int,
    public val maxOutputTokens: Int,
)

/**
 * Sampling parameters controlling how the engine selects the next token.
 *
 * The defaults are a balanced choice for general chat. For deterministic
 * tasks (summarization, structured extraction) set [temperature] to `0.0f`.
 *
 * @property temperature Softens or sharpens the next-token distribution.
 *   `0.0` = greedy; `1.0` = neutral; values above 1 produce more random output.
 * @property topK Sample only from the [topK] most likely tokens.
 *   `1` = greedy; `0` = disabled.
 * @property topP Sample only from tokens whose cumulative probability is at
 *   least [topP]. `1.0` = disabled.
 * @property maxTokens Hard upper bound on output tokens generated by a single
 *   [LlmEngine.generate] call.
 * @property stopTokens Tokens (as substrings) that, when produced, terminate
 *   generation early.
 */
public data class GenerationOptions(
    public val temperature: Float = DEFAULT_TEMPERATURE,
    public val topK: Int = DEFAULT_TOP_K,
    public val topP: Float = DEFAULT_TOP_P,
    public val maxTokens: Int = DEFAULT_MAX_TOKENS,
    public val stopTokens: List<String> = emptyList(),
) {
    /** Default sampling values used when no [GenerationOptions] are supplied. */
    public companion object {
        /** Default [temperature]. */
        public const val DEFAULT_TEMPERATURE: Float = 0.7f

        /** Default [topK]. */
        public const val DEFAULT_TOP_K: Int = 40

        /** Default [topP]. */
        public const val DEFAULT_TOP_P: Float = 0.9f

        /** Default [maxTokens]. */
        public const val DEFAULT_MAX_TOKENS: Int = 1024
    }
}
